api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sms/', views.SendSMS.as_view(), name='send_sms'),
    path('account/recharge', views.RechargeAccountView.as_view(), name='recharge_account'),
    path('recharge/verify', views.ConfirmTransacionView.as_view(), name='confirm_transaction'),
    path('airtime/recharge', views.AirtimeRechargeView.as_view(), name='airtime_recharge'),
    path('history/', views.HistoryView.as_view(), name='history'),
]

pusher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('messenger.urls'))
]

admin.site.site_header = 'Pusher Admin'
admin.site.site_title = 'Pusher Admin'

xms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('api.urls'), name='api'),
]

api/models.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Account(models.Model):
    user = models.OneToOneField(
        User, related_name='account', on_delete=models.CASCADE)
    balance = models.IntegerField(default=0)
    phone = models.IntegerField(null=True)

    def recharge(self, amount):
        """ Recharges User account """
        self.balance = self.balance + amount
        self.save()

    def deduct(self, amount):
        """ Deducts amount from user account """

        self.balance = self.balance - amount
        self.save()
    
    def can_make_transaction(self, amount):
        """ checks if a user can make a transaction """
        return self.balance >= amount


@receiver(post_save, sender=User)
def create_account(sender, **kwargs):
    if kwargs['created']:
        user_account = Account.objects.get_or_create(
            user=kwargs['instance']
        )

class Activity(models.Model):
    ACTIONS = (
        ('RC', 'Account TopUp'),
        ('SM', 'Send SMS'),
        ('AR', 'Airtime Recharge'),
    )
    STATUS = (
        ('P', 'PENDING'),
        ('S', 'SUCCESS'),
        ('F', 'FAILED')
    )

    action = models.CharField(choices=ACTIONS, max_length=2)
    status = models.CharField(choices=STATUS, max_length=1)
    user = models.ForeignKey(
        User, related_name='activities', on_delete=models.CASCADE)
    description = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    @classmethod
    def sms_sent(cls, username):
        """ Return Number of SMS Sent """
        return cls.objects.filter(
            user=User.objects.get(username=username)).filter(
                action='SM').filter(status='S').count()
    
    @classmethod
    def airtime_recharged(cls, username):
        """ Return Number of airtimes recharged """
        return cls.objects.filter(
            user=User.objects.get(username=username)).filter(
                action='AR').filter(status='S').count()
    
def success(request, action, description=None, message=None):
    """ Create a success Activity """
    messages.success(request, message)
    return Activity.objects.create(user=request.user, action=action, description=description, status='S')


def failed(request, action, description=None, message=None):
    """ Create a failed Activity """
    messages.error(request, message)
    return Activity.objects.create(user=request.user, action=action, description=description, status='F')


def pending(request, action, description=None, message=None):
    """ Create a pending Activity """
    messages.info(request, message)
    return Activity.objects.create(user=request.user, action=action, description=description, status='P')

api/forms.py
from allauth.account.forms import SignupForm
from django import forms

from libs import AIRTIME, CARD, SMS
from libs.sms import SMS

from .fields import (CreditCardField, ExpiryDateField, PhoneField,
                     VerificationValueField)


class SignUpForm(SignupForm):
    phone_number = PhoneField(required=True)

    default_field_order = [
        'username',
        'email',
        'email2',  # ignored when not present
        'password1',
        'password2'  # ignored when not present
        'phone'
    ]

    def signup(self, request, user):
        """ Sign up and create new user """
        account = user.account.phone = self.cleaned_data['phone']
        account.save()


class SMSForm(forms.Form):
    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': '070xxxxxxxxxxx'}
        ),
        label='Phone',
    )
    message = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'message'})
    )

    def clean_phone_number(self):
        telcoPrefixes = ['703', '706', '803', '806', '810', '813', '814', '816', '903', '705',
                         '805', '811', '815', '905', '701', '708', '802', '808', '812', '902',
                         '809', '817', '818', '909', '804']
        numbers = self.cleaned_data['phone_number'].split(',') if len(
            self.cleaned_data['phone_number']) > 1 else [self.cleaned_data['phone_number'], ]
        valid_numbers = []
        for number in numbers:
            if number[1:4] not in telcoPrefixes:
                raise forms.ValidationError(
                    f'{number} is not a valid Nigerian Phone number')
            valid_numbers.append(f'+234{number[1:]}')
        return valid_numbers

    def send_sms(self, sender):
        return SMS().send_sms_sync(
            self.cleaned_data['phone_number'],
            self.cleaned_data['message'],
            sender
        )


class PaymentForm(forms.Form):

    name_on_card = forms.CharField(max_length=50, required=True)
    card_number = CreditCardField(required=True)
    expiry_date = ExpiryDateField(required=True)
    cvv = VerificationValueField(required=True, label='CVV')
    pin = forms.IntegerField(
        required=True, max_value=9999,
        widget=forms.PasswordInput(
            attrs={'maxlength': 4, 'pattern': r"\d*"}),
        label='Pin')
    amount = forms.IntegerField(required=True)

    def make_payment(self):
        return CARD().checkout(
            self.cleaned_data['card_number'],
            self.cleaned_data['amount'],
            str(self.cleaned_data['pin']),
            self.cleaned_data['expiry_date'],
            int(self.cleaned_data['cvv']),

        )


class OTPForm(forms.Form):

    otp = forms.IntegerField(
        required=True, max_value=9999,
        widget=forms.PasswordInput(
            attrs={'maxlength': 4, 'pattern': r"\d*"}),
        label='OTP')

    def validate_payment(self, transaction_id):
        """ Validate Payment """
        return CARD().validate(
            transaction_id,
            self.cleaned_data['otp'],
        )


class RechargeAirtimeForm(forms.Form):
    phone_number = PhoneField(required=True)
    amount = forms.IntegerField(required=True)

    def clean_phone_number(self):
        phone = self.cleaned_data['phone_number']
        return f"+234{phone[1:]}"

    def send_airtime(self):
        return AIRTIME().send_single(
            self.cleaned_data['phone_number'],
            str(self.cleaned_data['amount']))

api/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from libs.sms import SMS

from .forms import OTPForm, PaymentForm, RechargeAirtimeForm, SMSForm
from .models import Activity, failed, pending, success


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['sms_sent'] = Activity.sms_sent(self.request.user.username)
            context['airtime_recharged'] = Activity.airtime_recharged(self.request.user.username)
        return context

@method_decorator(login_required, name='dispatch')
class SendSMS(FormView):
    template_name = 'api/send_sms.html'
    form_class = SMSForm
    success_url = reverse_lazy('api:send_sms')

    def form_valid(self, form):
        """ Checks if inputs are valid and sends the SMS """

        try:
            if not self.request.user.account.can_make_transaction(
                len(form.cleaned_data['phone_number']) * settings.COST_MESSAGE
            ):
                failed(self.request, 'AR', "Insufficient Balance",
                message="Insufficient Balance"
            )
                return redirect(reverse('api:index'))
            res = form.send_sms('08176410891')
            if res['SMSMessageData']['Recipients'][0]['status'].lower() != 'success':
                raise Exception('Could not send')
            # print(json.load(res))
        except Exception as e:
            failed(
                self.request, 'SM', ','.join(
                    form.cleaned_data['phone_number']),
                message="There was a problem sending your sms, Try again later"
            )
        else:
            self.request.user.account.deduct(
                len(form.cleaned_data['phone_number']) * settings.COST_MESSAGE)
            success(
                self.request, 'SM', ','.join(form.cleaned_data['phone_number']),
                message=(f"Your SMS to {form.cleaned_data['phone_number']} was sent"
                         "successfully"
                         ))
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class AirtimeRechargeView(FormView):
    form_class = RechargeAirtimeForm
    template_name = 'api/airtime_recharge.html'
    success_url = reverse_lazy('api:airtime_recharge')

    def form_valid(self, form):
        if not self.request.user.account.can_make_transaction(
            form.cleaned_data['amount']
        ):
            failed(self.request, 'AR', "Insufficient Balance",
                message="Insufficient Balance"
            )
            return redirect(reverse('api:index'))
        res = None
        try:
            res = form.send_airtime()

        except Exception as e:
            failed(self.request, 'AR', form.cleaned_data['phone_number'],
                message="Could not complete Airtime Recharge, try again later"
            )
        else:
            success(self.request, 'AR', form.cleaned_data['phone_number'],
            message=f"Your recharge of N{form.cleaned_data['amount']} was successful"
            )
            self.request.user.account.deduct(form.cleaned_data['amount'])
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class RechargeAccountView(FormView):
    form_class = PaymentForm
    template_name = 'api/recharge_account.html'
    success_url = reverse_lazy('api:confirm_transaction')
    failure_url = reverse_lazy('api:sms_failure')

    def form_valid(self, form):
        res = None
        try:
            res = form.make_payment()
        except Exception as e:
            failed(self.request, 'RC', message="Could not complete Transaction. Try again later")
        else:
            # If transaction has already being initialized
            pending(self.request, 'RC', message=("an OTP was sent to your registered number, "
            "enter it to continue"))
            if res['status'] == 'DuplicateRequest':
                return redirect('api:confirm_transaction')
            self.request.session['transaction_id'] = res['transactionId']
            self.request.session['recharge_amount'] = form.cleaned_data['amount']
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class ConfirmTransacionView(FormView):
    form_class = OTPForm
    template_name = 'api/otp.html'
    success_url = reverse_lazy('api:index')

    def get(self, request, *args, **kwargs):
        """Handle GET requests: If a transaction has not being initialized
            redirect user to payment form
        """
        if request.session.get('transaction_id', None) is None:
            return redirect('api:recharge_account')
        return self.render_to_response(self.get_context_data())

    def form_valid(self, form):
        res = None
        try:
            res = form.validate_payment(self.request.session['transaction_id'])
            if res['status'] != 'Success':
                raise Exception('Failed')
        except Exception as e:
            failed(self.request, 'RC', self.request.session['recharge_amount'],
            message="Transaction Failed. Try again later")
        else:
            success(self.request, 'RC', self.request.session['recharge_amount'],
                "Transaction Successful"
            )
            self.request.user.account.recharge(
                self.request.session['recharge_amount'])
            self.request.session['checkout_token'] = res['checkoutToken']
        del self.request.session['transaction_id']
        del self.request.session['recharge_amount']
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class HistoryView(TemplateView):
    template_name = 'api/history.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['activities'] = Activity.objects.filter(
            user=self.request.user).order_by('-date')
        return context

api/templates/api/airtime_recharge.html
{% extends 'base.html' %}
{% load beautify %}
{% block content %}
<div class="container mt-5 py-3">
  <div class="row row justify-content-md-center">
    <div class="col-md-4">
      <div class="my-2">
        <h4>Recharge Your Phone</h4>
        
        <form method="POST">
          {% for field in form %}
          {% csrf_token %}
          {% if field.errors %}
          <div class="alert alert-danger alert-dismissible fade show" role='alert'>
            {{ field.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field|add_class:'form-control' }}
          </div>
          {% endfor %}
          <div class="form-group">
            <input type="submit" class="btn btn-outline-default" value="Send">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

api/templates/api/history.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div class="container- my-5 py-3 text-center">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Transaction</th>
                <th scope="col">Status</th>
                <th scope="col">Description</th>
            </tr>
        </thead>
        <tbody>
            {% for activity in activities %}
                <tr>
                    <th scope="row">{{ activity.date|naturaltime }}</th>
                    <td>{{ activity.get_action_display }}</td>
                    <td>{{ activity.get_status_display }}</td>
                    <td>{{ activity.description }}</td>
                </tr>
            {% empty %}
                You have no activities yet
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

api/templates/api/otp.html
{% extends 'base.html' %}
{% load beautify %}
{% block content %}
<div class="container mt-5 py-3">
  <div class="row row justify-content-md-center">
    <div class="col-md-4">
      <div class="my-2">
        <h4>Enter the OTP </h4>
        Enter OTP sent to your registered phone number
        <form method="POST">
          {% for field in form %}
          {% csrf_token %}
          {% if field.errors %}
          <div class="alert alert-danger alert-dismissible fade show" role='alert'>
            {{ field.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field|add_class:'form-control' }}
          </div>
          {% endfor %}
          <div class="form-group">
            <input type="submit" class="btn btn-outline-default" value="Send">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

api/templates/api/recharge_account.html
{% extends 'base.html' %}
{% load beautify %}
{% block content %}
<div class="container mt-5 py-3">
  <div class="row row justify-content-md-center">
    <div class="col-md-4">
      <div class="my-2">
        <div class="my-2">
          <h4>Top Up Your Account </h4>
          Use Your Credit Card to Recharge your account
        </div>
        <form method="POST">
          {% for field in form %}
          {% csrf_token %}
          {% if field.errors %}
          <div class="alert alert-danger alert-dismissible fade show" role='alert'>
            {{ field.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field|add_class:'form-control' }}
          </div>
          {% endfor %}
          <div class="form-group">
            <input type="submit" class="btn btn-outline-default" value="Send">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

api/templates/api/send_sms.html
{% extends 'base.html' %}
{% load beautify %}
{% block content %}
<div class="container mt-5 py-3">
  <div class="row row justify-content-md-center">
    <div class="col-md-4">
      <div class="my-2">
        <div class='my-2'>
          <h4>Send SMS </h4>
          To Send To multiple Clients just separate with a comma
        </div>
        <form method="POST">
          {% for field in form %}
          {% csrf_token %}
          {% if field.errors %}
          <div class="alert alert-danger alert-dismissible fade show" role='alert'>
            {{ field.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field|add_class:'form-control' }}
          </div>
          {% endfor %}
          <div class="form-group">
            <input type="submit" class="btn btn-outline-default" value="Send">
          </div>
        </form>
      </div>
    </div>

  </div>
</div>
{% endblock %}