api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sms/', views.SendSMS.as_view(), name='send_sms'),
    path('account/recharge', views.RechargeAccountView.as_view(), name='recharge_account'),
    path('recharge/verify', views.ConfirmTransacionView.as_view(), name='confirm_transaction'),
    path('airtime/recharge', views.AirtimeRechargeView.as_view(), name='airtime_recharge'),
    path('history/', views.HistoryView.as_view(), name='history'),
]

pusher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('messenger.urls'))
]

admin.site.site_header = 'Pusher Admin'
admin.site.site_title = 'Pusher Admin'

xms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('api.urls'), name='api'),
]

libs/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>xms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="mainNav">
        <a class="navbar-brand" href="{% url 'api:index' %}">xms</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'api:index' %}">
                        <i class="fas fa-fw fa-user"></i>
                        Dashboard
                    </a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'api:history' %}">
                            <i class="fas fa-fw fa-history"></i>
                            History
                        </a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">
                        <i class="fas fa-fw fa-sign-out-alt"></i>
                        Logout
                    </a>
                </li>
                
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">
                        <i class="fas fa-fw fa-user-check"></i> Register
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">
                        <i class="fas fa-fw fa-sign-in-alt"></i> Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% include 'messages.html' %}
    {% block content %}

    {% endblock %}
    <footer class="sticky-footer fixed-bottom bg-primary text-light">
        <div class="container">
            <div class="text-center">
                <small>Copyright © xms 2018</small>
            </div>
        </div>
    </footer>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

libs/templates/dashboard.html
{% load static %}
{% block content %}
<div class="container my-5 py-5">
  <div class="container bg-light p-3 my-5">
    <div class="d-flex justify-content-between">
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Account Balance</h6>
          <small class="text-muted">This is your account balance</small>
        </div>
        <span class="text-muted ml-5">&#8358; {{ request.user.account.balance }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">SMS Sent</h6>
          <small class="text-muted">number of SMS Sent</small>
        </div>
        <span class="text-muted ml-5">{{ sms_sent}}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Airtimes Recharged</h6>
          <small class="text-muted">Total Number of Airtimes Recharged</small>
        </div>
        <span class="text-muted ml-5">{{ airtime_recharged }}</span>
      </li>
    </div>
  </div>
  <div class="d-flex justify-content-between lh-condensed flex-md-wrap">
    <div class="col-md-4 text-center d-flex justify-content-center">
      <a href="{% url 'api:recharge_account' %}" class="text-dark cards my-1">
        <div class="card p-2" style="width: 18rem;">
          <div class="card-img-top text-center">
            <li class="fas fa-credit-card fa-5x"></li>
          </div>
          <div class="card-body">
            <h5 class="card-title">Recharge Account</h5>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4 text-center d-flex justify-content-center">
      <a href="{% url 'api:send_sms' %}" class="text-dark cards my-1">
        <div class="card p-2" style="width: 18rem;">
          <div class="card-img-top text-center">
            <li class="fas fa-paper-plane fa-5x"></li>
          </div>
          <div class="card-body">
            <h5 class="card-title">Send SMS</h5>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4 text-center d-flex justify-content-center">
      <a href="{% url 'api:airtime_recharge' %}" class="text-dark cards my-1">
        <div class="card p-2" style="width: 18rem;">
          <div class="card-img-top text-center">
            <li class="fas fa-mobile-alt fa-5x"></li>
          </div>
          <div class="card-body">
            <h5 class="card-title">Recharge Phone</h5>
          </div>
        </div>
      </a>
    </div>
  </div>

</div>
{% endblock %}

libs/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not request.user.is_authenticated %}
<div class="container-fluid bg-primary mb-3 py-5">
  <div class="row">
    <div class="col-md-7 d-flex align-items-center justify-content-center">
      <div class="text-center">
        <h4>Send Your SMS Without using your mobile Airtime</h4>
        Recharge your SMS bank and send SMS without stress
      </div>
    </div>
    <div class="col-md-5">
      <div class="my-2">
        <img src="{% static 'images/page-shot.png' %}" class="img-fluid" />
      </div>
    </div>>
  </div>
</div>
<div class="container mb-5">
  <div class="row">
    <div class="col-md-4 bg-light p-5 text-center">
      <i class="fas fa-credit-card fa-5x"></i>
      <div>
        Fast Airtime Recharge
        Recharge Your Line with just a Click
      </div>
      <a href="{% url 'account_signup' %}" class="btn btn-secondary">Recharge Now</a>
    </div>
    <div class="col-md-4 p-5 bg-secondary text-center">
      <i class="fas fa-mobile-alt fa-5x"></i>
      <div>
        Send SMS Easily
        Enter the Phone Number and text with a click your SMS is delivered with your number
      </div>
      <a href="{% url 'account_signup' %}" class="btn btn-primary">Send SMS</a>
    </div>
    <div class="col-md-4 p-5 bg-light text-center">
      <i class="fas fa-envelope fa-5x"></i>
      <div>
        Send bulk SMS Easily
        Deliver your SMS to a large number of people. Save a contact lists and send
      </div>
      <a href="{% url 'account_signup' %}" class="btn btn-secondary">Get Started</a>
    </div>
  </div>
</div>
{% else %}
{% include 'dashboard.html' %}
{% endif %}
{% endblock %}

libs/templates/messages.html
{% if messages %}
<div class="container mt-5">
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}